#!/bin/bash

# 顏色定義
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# 找到專案根目錄
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

# 配置
BACKEND_PORT=8080
LOBBY_PORT=3001
LOBBY_CLIENT_PORT=5174
GAME_CLIENT_PORT=5175

LOBBY_TUNNEL_LOG="tunnel-lobby.log"
GAME_TUNNEL_LOG="tunnel-game.log"

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}  麻將遊戲 - 分離式 Tunnel 啟動${NC}"
echo -e "${BLUE}============================================${NC}"
echo -e "${YELLOW}專案目錄: $SCRIPT_DIR${NC}"
echo ""

# 清理函數
cleanup() {
    echo ""
    echo -e "${YELLOW}正在停止所有服務...${NC}"
    kill $BACKEND_PID $LOBBY_PID $LOBBY_CLIENT_PID $GAME_CLIENT_PID $LOBBY_TUNNEL_PID $GAME_TUNNEL_PID 2>/dev/null
    pkill -P $$ 2>/dev/null
    # 還原 .env 檔案
    if [ -f "lobby-client/.env.backup" ]; then
        mv lobby-client/.env.backup lobby-client/.env
    fi
    echo -e "${GREEN}✓ 所有服務已停止${NC}"
    exit 0
}

trap cleanup SIGINT SIGTERM

# 檢查 cloudflared
if ! command -v cloudflared &> /dev/null; then
    echo -e "${RED}✗ cloudflared 未安裝${NC}"
    echo -e "${YELLOW}請運行: make install-cloudflared${NC}"
    exit 1
fi

# 備份原始 .env
if [ -f "lobby-client/.env" ]; then
    cp lobby-client/.env lobby-client/.env.backup
fi

# 1. 啟動後端服務器
echo -e "${YELLOW}🚀 啟動後端服務器 (Port $BACKEND_PORT)...${NC}"
(cd "$SCRIPT_DIR/server" && LOBBY_INTERNAL_SECRET=dev-internal-secret go run cmd/main.go > "$SCRIPT_DIR/server.log" 2>&1) &
BACKEND_PID=$!
sleep 2

if ! kill -0 $BACKEND_PID 2>/dev/null; then
    echo -e "${RED}✗ 後端服務器啟動失敗${NC}"
    exit 1
fi
echo -e "${GREEN}✓ 後端服務器已啟動${NC}"

# 2. 啟動遊戲前端
echo -e "${YELLOW}🎮 啟動遊戲前端 (Port $GAME_CLIENT_PORT)...${NC}"
(cd "$SCRIPT_DIR/game-client" && npm run dev > "$SCRIPT_DIR/game-client.log" 2>&1) &
GAME_CLIENT_PID=$!
sleep 3

if ! kill -0 $GAME_CLIENT_PID 2>/dev/null; then
    echo -e "${RED}✗ 遊戲前端啟動失敗${NC}"
    cleanup
    exit 1
fi
echo -e "${GREEN}✓ 遊戲前端已啟動${NC}"

# 3. 啟動遊戲 Tunnel（先啟動，因為需要 URL 給 Lobby server）
echo -e "${YELLOW}🌐 啟動遊戲 Tunnel...${NC}"
cloudflared tunnel --url http://localhost:$GAME_CLIENT_PORT > "$GAME_TUNNEL_LOG" 2>&1 &
GAME_TUNNEL_PID=$!

# 等待獲取遊戲 Tunnel URL
TIMEOUT=30
COUNT=0
GAME_TUNNEL_URL=""

while [ $COUNT -lt $TIMEOUT ]; do
    GAME_TUNNEL_URL=$(grep -oP 'https://[a-z0-9-]+\.trycloudflare\.com' "$GAME_TUNNEL_LOG" 2>/dev/null | head -1)
    if [ ! -z "$GAME_TUNNEL_URL" ]; then
        break
    fi
    sleep 1
    COUNT=$((COUNT + 1))
done

if [ -z "$GAME_TUNNEL_URL" ]; then
    echo -e "${RED}✗ 無法獲取遊戲 Tunnel URL${NC}"
    cleanup
    exit 1
fi
echo -e "${GREEN}✓ 遊戲 Tunnel: $GAME_TUNNEL_URL${NC}"

# 4. 啟動 Lobby 伺服器（使用遊戲 Tunnel URL）
echo -e "${YELLOW}🏠 啟動 Lobby 伺服器 (Port $LOBBY_PORT)...${NC}"
(cd "$SCRIPT_DIR/server" && GAME_CLIENT_URL=$GAME_TUNNEL_URL go run cmd/lobby/main.go > "$SCRIPT_DIR/lobby.log" 2>&1) &
LOBBY_PID=$!
sleep 2

if ! kill -0 $LOBBY_PID 2>/dev/null; then
    echo -e "${RED}✗ Lobby 伺服器啟動失敗${NC}"
    cleanup
    exit 1
fi
echo -e "${GREEN}✓ Lobby 伺服器已啟動 (GAME_CLIENT_URL=$GAME_TUNNEL_URL)${NC}"

# 5. 更新 lobby-client/.env
echo -e "${YELLOW}📝 更新 lobby-client 環境變量...${NC}"
cat > lobby-client/.env << EOF
# Development environment variables (auto-generated by start-tunnel-all.sh)
VITE_GAME_SERVER_URL=$GAME_TUNNEL_URL
EOF
echo -e "${GREEN}✓ 已設定 VITE_GAME_SERVER_URL=$GAME_TUNNEL_URL${NC}"

# 6. 啟動 Lobby 前端
echo -e "${YELLOW}🏠 啟動大廳前端 (Port $LOBBY_CLIENT_PORT)...${NC}"
(cd "$SCRIPT_DIR/lobby-client" && npm run dev > "$SCRIPT_DIR/lobby-client.log" 2>&1) &
LOBBY_CLIENT_PID=$!
sleep 3

if ! kill -0 $LOBBY_CLIENT_PID 2>/dev/null; then
    echo -e "${RED}✗ 大廳前端啟動失敗${NC}"
    cleanup
    exit 1
fi
echo -e "${GREEN}✓ 大廳前端已啟動${NC}"

# 7. 啟動大廳 Tunnel
echo -e "${YELLOW}🌐 啟動大廳 Tunnel...${NC}"
cloudflared tunnel --url http://localhost:$LOBBY_CLIENT_PORT > "$LOBBY_TUNNEL_LOG" 2>&1 &
LOBBY_TUNNEL_PID=$!

# 等待獲取大廳 Tunnel URL
TIMEOUT=30
COUNT=0
LOBBY_TUNNEL_URL=""

while [ $COUNT -lt $TIMEOUT ]; do
    LOBBY_TUNNEL_URL=$(grep -oP 'https://[a-z0-9-]+\.trycloudflare\.com' "$LOBBY_TUNNEL_LOG" 2>/dev/null | head -1)
    if [ ! -z "$LOBBY_TUNNEL_URL" ]; then
        break
    fi
    sleep 1
    COUNT=$((COUNT + 1))
done

if [ -z "$LOBBY_TUNNEL_URL" ]; then
    echo -e "${RED}✗ 無法獲取大廳 Tunnel URL${NC}"
    cleanup
    exit 1
fi
echo -e "${GREEN}✓ 大廳 Tunnel: $LOBBY_TUNNEL_URL${NC}"

# 顯示成功訊息
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}✓ 所有服務已成功啟動！${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "${BLUE}📍 本地訪問:${NC}"
echo -e "   後端:     ${YELLOW}http://localhost:$BACKEND_PORT${NC}"
echo -e "   Lobby:    ${YELLOW}http://localhost:$LOBBY_PORT${NC}"
echo -e "   大廳前端: ${YELLOW}http://localhost:$LOBBY_CLIENT_PORT${NC}"
echo -e "   遊戲前端: ${YELLOW}http://localhost:$GAME_CLIENT_PORT${NC}"
echo ""
echo -e "${BLUE}🌐 公網訪問 (分享此連結給朋友):${NC}"
echo -e "   ${GREEN}$LOBBY_TUNNEL_URL${NC}"
echo ""
echo -e "${BLUE}📝 Tunnel 對應:${NC}"
echo -e "   大廳: $LOBBY_TUNNEL_URL → localhost:$LOBBY_CLIENT_PORT"
echo -e "   遊戲: $GAME_TUNNEL_URL → localhost:$GAME_CLIENT_PORT"
echo ""
echo -e "${YELLOW}提示:${NC}"
echo -e "  • 按 ${RED}Ctrl+C${NC} 停止所有服務"
echo -e "  • 日誌: server.log, lobby.log, lobby-client.log, game-client.log"
echo -e "  • Tunnel 日誌: $LOBBY_TUNNEL_LOG, $GAME_TUNNEL_LOG"
echo ""

# 嘗試打開瀏覽器
if command -v xdg-open &> /dev/null; then
    xdg-open "$LOBBY_TUNNEL_URL" &
elif command -v open &> /dev/null; then
    open "$LOBBY_TUNNEL_URL" &
fi

# 等待所有進程
wait
